### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by Syfer** [adhearsion/virginia#22]
/ruby-2.2.1/gems/virginia-0.5.1/lib/virginia/plugin.rb:8:in `block in <class:Plugin>': uninitialized constant Virginia::Plugin::Service (NameError)

**Comment by bklang** [comment]
Can you tell me more about how you are encountering this? I've not seen it in my apps and the unit tests don't exhibit the problem.  If you can share the app, or a portion of the app, where you see this, it would be helpful.

**Comment by Syfer** [comment]
It's new, simple and blank adhearsion application. Added two lines in Gemfile:
gem 'virginia'
gem 'sinatra'

Thats all.

'ahn start' and got this error

**Comment by bklang** [comment]
@Syfer Would you paste full console output? I did get an "uninitialized constant" error, but not the one you got:

```
$ ahn -
/Users/bklang/.rvm/gems/ruby-2.1.3/gems/reel-0.5.0/lib/reel/response.rb:10:in `<class:Response>': uninitialized constant HTTP::Response::STATUS_CODES (NameError)
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/reel-0.5.0/lib/reel/response.rb:4:in `<module:Reel>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/reel-0.5.0/lib/reel/response.rb:3:in `<top (required)>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/reel-0.5.0/lib/reel.rb:12:in `require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/reel-0.5.0/lib/reel.rb:12:in `<top (required)>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia/service.rb:2:in `require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia/service.rb:2:in `<top (required)>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia.rb:7:in `require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia.rb:7:in `block in <top (required)>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia.rb:7:in `each'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/virginia-0.5.1/lib/virginia.rb:7:in `<top (required)>'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/bklang/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/bklang/tmp/ahnapp/config/environment.rb:8:in `<top (required)>'
	from script/ahn:4:in `require'
	from script/ahn:4:in `<main>'

```

The one I got is a [known issue](https://github.com/celluloid/reel/issues/213) and will be fixed shortly.

Please also let me know which version of Ruby you are running as well as any other environmental information, such as host operating system.

**Comment by Syfer** [comment]
I will provide output little later, but for now i can say that i have ruby 2.2.1

**Comment by Syfer** [comment]
root@localhost:/var/ruby/test# ahn start
Starting Adhearsion server at /var/ruby/test
[2015-12-08 17:41:38.924] INFO  Adhearsion::Console: Launching Adhearsion Console
AHN> [2015-12-08 17:41:38.946] INFO  Adhearsion::PunchblockPlugin::Initializer: Starting connection to server
[2015-12-08 17:41:38.959] INFO  Punchblock::Connection::XMPP: Connected to XMPP as ivr@127.0.0.1/localhost-39875
[2015-12-08 17:41:38.961] INFO  Adhearsion::PunchblockPlugin::Initializer: Connected to Punchblock server
[2015-12-08 17:41:38.962] INFO  Adhearsion::Process: Transitioning from booting to running with 0 active calls due to booted event.
[2015-12-08 17:41:38.963] INFO  Virginia::Plugin: Virginia has been loaded
[2015-12-08 17:41:38.963] DEBUG Celluloid: Terminating 3 actors...
/usr/local/rvm/gems/ruby-2.2.1/gems/virginia-0.5.1/lib/virginia/plugin.rb:8:in `block in <class:Plugin>': uninitialized constant Virginia::Plugin::Service (NameError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/plugin/initializer.rb:26:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/plugin/initializer.rb:26:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/plugin.rb:188:in `block in run_plugins'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/plugin.rb:187:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/plugin.rb:187:in `run_plugins'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/initializer.rb:254:in `run_plugins'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/initializer.rb:66:in `block in start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/initializer.rb:41:in `catch'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/initializer.rb:41:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/initializer.rb:12:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/cli_commands/ahn_command.rb:104:in `start_app'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/adhearsion-2.6.2/lib/adhearsion/cli_commands/ahn_command.rb:43:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from script/ahn:9:in `<main>'

**Comment by benlangfeld** [comment]
@Syfer Please also consider testing the Adhearsion 3 pre-release which comes with a built-in HTTP server to replace Virginia. Testing help is appreciated to get is closer to a final 3.0.0 release.
